### ISSUE TITLE
Error in clf_controller

### ISSUE THREAD

**Issue by camontblanc** [dawsonc/neural_clbf#3]
Hi!

I am trying to reproduce your results, however in line 281 in file `clf_controller.py` there is an error `gurobipy.GurobiError: Incompatible dimensions` when adding the CLF constraints and the relax variables in the QP.

I would really appreciate if you could walk me through this!

Warm regards,
Carlos.

**Comment by dawsonc** [comment]
Hi!

I think this is due to incompatible versions. I've updated the requirements file to specify exact versions for `gurobipy` and `torch` (as of commit c7431e0). Please try installing these requirements in your conda environment and see if it resolves the issue.

Thanks,
- Charles

**Comment by dawsonc** [comment]
Closing; a similar issue was reported via email and resolved by fixing the versions of `gurobipy` and `torch`.
